name: gif_project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.1.0
  dio: ^4.0.6
  anim_search_bar: ^2.0.2
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  downloads_path_provider_28: ^0.1.2
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
