name: gif_project
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_offline: ^2.1.0
  dio: ^4.0.6
  anim_search_bar: ^2.0.2
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  downloads_path_provider_28: ^0.1.2
  intl: ^0.17.0
  share_plus: ^4.0.4
  google_fonts: ^2.3.2
  get: ^4.6.1
  url_launcher: ^6.1.2
  flutter_native_splash: ^2.1.6
  google_mobile_ads: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0 
  change_app_package_name: ^1.0.0
  icons_launcher: ^1.1.7

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true


flutter_icons:
  image_path: 'assets/images/logo.png'
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
